/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Airdrop', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Airdrop__factory>
getContractFactory(name: 'Nocenite', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Nocenite__factory>
getContractFactory(name: 'Nocenix', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Nocenix__factory>

  getContractAt(name: 'Airdrop', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Airdrop>
getContractAt(name: 'Nocenite', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Nocenite>
getContractAt(name: 'Nocenix', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Nocenix>

  deployContract(name: 'Airdrop', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Airdrop>
deployContract(name: 'Nocenite', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Nocenite>
deployContract(name: 'Nocenix', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Nocenix>

  deployContract(name: 'Airdrop', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Airdrop>
deployContract(name: 'Nocenite', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Nocenite>
deployContract(name: 'Nocenix', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Nocenix>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  